version: "3.8"

services:
  db:
    container_name: autospacce_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: autospacce
      POSTGRES_PASSWORD: mysecret
    volumes:
      - db_data_autospace:/var/lib/postgresql/data
volumes:
  db_data_autospace:
